### ISSUE TITLE
Display future reservations in addition to running reservations

### ISSUE THREAD

**Issue by pfisterer** [wisebed/wisegui#49]
Currently, only running reservations are displayed when one clicks on "My Reservations". 

In addition, future reservations should be shown and they should also be editable (and deleteable).

**Comment by danbim** [comment]
It would be nice to have that dropdown split in three areas. One for past, one for current and one for future reservations.

With the currently released version of TR, it doesn't make sense to implement this feature as you can only connect to currently running reservations. This behavior will change in the future so that the user is either able to schedule operations for future reservations or to retrieve data from past reservations again. Therefore the implementation of this feature should be done in the "tr-0.9" branch of WiseGui which is included in the current TR develop branch (i.e. the current develop branch embeds the WiseGui and right after starting the portal server you can use the WiseGui with the local testbed).

**Comment by danbim** [comment]
@master-lincoln are you still aware of this issue? should also be implemented soon...

**Comment by master-lincoln** [comment]
Does the API already support this, i.e. deleting and editing? And currently [a range needs to be passed](https://github.com/wisebed/wisegui/blob/master/js/wisebed.js#L77) to get the reservations. How would I get all future reservations? A wokaround could be setting the `to` date to a year from now or sth., but I don't know about the performance drawback...

**Comment by MrMarvin** [comment]
> Does the API already support this, i.e. deleting and editing?

As far as I know from implementing this in IOTHub: No, it does not.

>  A wokaround could be setting the to date to a year from now

Correct approach imo, do not hesitate to do it that way. I guess the backend will be efficient enough to cope with such requests.

**Comment by master-lincoln** [comment]
> Correct approach imo, do not hesitate to do it that way. I guess the backend will be efficient enough to cope with such requests.

I can implement displaying future reservations then, but you should have a look @danbim for the backend part to delete/edit future reservations

**Comment by danbim** [comment]
Judging from a look at the RS API an edit can be done by deleteReservation, followed by makeReservation. So the backend supports this. Regarding the efficiency of the backend you should not worry. Always implement against the interface, not the implementation ;-). This basically means that if the backend should have a performance issue here we should adapt the implementation of it by, e.g. caching the results, not worry about it in the client that just adheres to what the API specifies.

The only thing that you'll have to worry might be the number of reservations that are potentially returned so they're hard to display in the GUI. This might actually be an API issue, so I've added an issue to add `offset` and `amount` parameters to the RS API: https://github.com/wisebed/api-wsdl/issues/76.

**Comment by danbim** [comment]
Just implemented the API changes in the https://github.com/wisebed/api-wsdl/, https://github.com/wisebed/api-java/ and https://github.com/itm/testbed-runtime. Also, the REST API was updated to allow the new parameters so you can start to code against the API. Please note that the backend currently ignores these parameters (i.e. they are not passed through to the persistence layer) but I've update the TR implementation so that it compiles and can be started.

In order to run the Testbed Runtime portal server (which embeds WiseGui in the tr-0.9 branch) please execute `./run-portal.sh portal-embedded-minimal.properties` in the directory `etc/configs/portal` of TR (after adapting the configuration file to your database setup. Then you can start coding on WiseGui in the most comfortable, pleasing way ever ;-).

**Comment by danbim** [comment]
Now obsolete, see #73
